
package vue;
import model.*;
import controller.Factory_fourniture;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

public class FormFourniture extends javax.swing.JFrame {
ArrayList<Fourniture> listefourn=new ArrayList();
JTable tbf;
Fourniture fourn=null;
private final DefaultTableModel model;
   
    public FormFourniture() {
        initComponents();
    model=new DefaultTableModel();
    model.addColumn("Nom");
    model.addColumn("Quantiter");
    model.addColumn("origine");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomfour = new javax.swing.JLabel();
        quantite = new javax.swing.JLabel();
        origine = new javax.swing.JLabel();
        tnom = new javax.swing.JTextField();
        tquantite = new javax.swing.JTextField();
        torigine = new javax.swing.JTextField();
        enregistrer = new javax.swing.JButton();
        afficher = new javax.swing.JButton();
        reinicialiser = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        trecherche = new javax.swing.JTextField();
        recherche = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomfour.setText("Nom de la fourniture ");

        quantite.setText("Quantites");

        origine.setText("Origine");

        tquantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tquantiteActionPerformed(evt);
            }
        });

        enregistrer.setText("Add");
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });

        afficher.setText("View");
        afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherActionPerformed(evt);
            }
        });

        reinicialiser.setText("Reset");
        reinicialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinicialiserActionPerformed(evt);
            }
        });

        modifier.setText("Update");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setText("Delete");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        recherche.setText("Research");
        recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(origine, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomfour))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tquantite)
                            .addComponent(tnom)
                            .addComponent(torigine, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(trecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(enregistrer)
                                .addGap(45, 45, 45)
                                .addComponent(afficher)
                                .addGap(67, 67, 67)
                                .addComponent(reinicialiser)
                                .addGap(46, 46, 46)
                                .addComponent(modifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addComponent(supprimer)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomfour, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tquantite, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origine, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torigine, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enregistrer)
                    .addComponent(afficher)
                    .addComponent(reinicialiser)
                    .addComponent(modifier)
                    .addComponent(supprimer))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tquantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tquantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tquantiteActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
    if (evt.getSource()==modifier)
     {
         String no = tnom.getText();
         int quant = Integer.parseInt(tquantite.getText());
         String ori = torigine.getText();
        

     
   fourn = new Fourniture(no,quant,ori);
   Factory_fourniture.modifFourniture(fourn,tnom.getText());
   affichage();
    }
    }//GEN-LAST:event_modifierActionPerformed

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        if (evt.getSource()==enregistrer)
     {
         String no = tnom.getText();
         int quant = Integer.parseInt(tquantite.getText());
         String ori = torigine.getText();
        

     
   fourn = new Fourniture(no,quant,ori);
   Factory_fourniture.insererFourniture(fourn);
   affichage();
    }
    }//GEN-LAST:event_enregistrerActionPerformed

    private void afficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherActionPerformed
         if(evt.getSource()==afficher) 
       {affichage();}
    }//GEN-LAST:event_afficherActionPerformed

    private void reinicialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinicialiserActionPerformed
        if(evt.getSource()==reinicialiser) 
       {effacer();}
    }//GEN-LAST:event_reinicialiserActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        if(fourn!=null)
            {
                String msg="Voulez-vous reelement supprimer la fourniture "+fourn.getNom_fourn()+"?";
                int rep = JOptionPane.showConfirmDialog(null, msg);
                if(rep ==0)
                {
                    Factory_fourniture.deleteFourniture(fourn);
                    affichage();
                    effacer();
                }

            }
    }//GEN-LAST:event_supprimerActionPerformed

      public void recupinfo(Fourniture fou){
        
       
       tnom.setText(fou.getNom_fourn());
       tquantite.setText(String.valueOf(fou.getQuantite()));
       torigine.setText(fou.getOrigine());
       
       
       
   }
    private void rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheActionPerformed
            if(evt.getSource()==recherche)
            {
                String rch=trecherche.getText();
                fourn= Factory_fourniture.getRechC(rch);
                if(fourn !=null)
                {
                    recupinfo(fourn);
                    
                                  
                }
                
            }
    }//GEN-LAST:event_rechercheActionPerformed

    public void affichage()
 {
     model.setRowCount(0);
     listefourn = Factory_fourniture.getFourniture();
     for(Fourniture fourn :listefourn)
     {  
         // JLabel id_malade,nom,prenom,genre,adresse,nationalite,numero;
         model.addRow(new Object[]{
            fourn.getNom_fourn(),fourn.getQuantite(),fourn.getOrigine()
         });
     }
     tbf = new JTable(model);
     JScrollPane p = new JScrollPane(tbf);
     p.setBounds(10,500,800,100);
     this.getContentPane().add(p);
 }
    
     public void effacer()
 {
     tnom.setText("");
     tquantite.setText("");
     torigine.setText("");
    
 }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFourniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFourniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFourniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFourniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFourniture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afficher;
    private javax.swing.JButton enregistrer;
    private javax.swing.JButton modifier;
    private javax.swing.JLabel nomfour;
    private javax.swing.JLabel origine;
    private javax.swing.JLabel quantite;
    private javax.swing.JButton recherche;
    private javax.swing.JButton reinicialiser;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField tnom;
    private javax.swing.JTextField torigine;
    private javax.swing.JTextField tquantite;
    private javax.swing.JTextField trecherche;
    // End of variables declaration//GEN-END:variables
}
